version: '2'
services:

  db:
    image: mongo:3.4

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "3000:3000"
    env_file: ./.env
    depends_on:
      - db

  app:
    image: nginx:1.11
    volumes:
      - ./app/public:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - api
